#include "gba.h"
#include "logic.h"
#include "draw.h"
#include "myLib.h"
#include "ramranch_audio.h"
#include "images/ramranch.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

#include <stdio.h>
#include <stdlib.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
    APP_INIT,
    APP,
    APP_EXIT,
    APP_EXIT_NODRAW,
} GBAState;

int main(void) {
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    fillScreenDMA(0xBDF7);
    drawString(2, 2, "eat my asshole", 0x1F);
    drawImageDMA(0, 0, 240, 160, ramranch);

    /* create custom interrupt handler for vblank - whole point is to turn off sound at right time
    * we disable interrupts while changing them, to avoid breaking things */
                                                                   *interrupt_enable = 0;
    //*interrupt_callback = (unsigned int) &on_vblank;
    //*interrupt_selection |= INTERRUPT_VBLANK;
    //*display_interrupts |= 0x08;
    //*interrupt_enable = 1;

    /* clear the sound control initially */
    *sound_control = 0;



    play_sound(ramranch_data, ramranch_length, 8000, 'A');

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    while (1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
            case START:
                // Wait for VBlank
                waitForVBlank();
                if (vBlankCounter % 100 == 0) {
                    drawString(10, 20, "RAM RANCH IS UNDER SIEGE", 0x0000);
                }
                if (vBlankCounter % 220 == 0) {
                    drawImageDMA(0, 0, 240, 160, ramranch);
                }


                // TA-TODO: Draw the start state here.

                // state = START_NODRAW;
                break;
            case START_NODRAW:
                // TA-TODO: Check for a button press here to start the app.
                // Start the app by switching the state to APP_INIT.

                break;
            case APP_INIT:
                // Initialize the app. Switch to the APP state.
                initializeAppState(&currentAppState);

                // Draw the initial state of the app
                fullDrawAppState(&currentAppState);

                state = APP;
                break;
            case APP:
                // Process the app for one frame, store the next state
                nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

                // Wait for VBlank before we do any drawing.
                waitForVBlank();

                // Undraw the previous state
                undrawAppState(&currentAppState);

                // Draw the current state
                drawAppState(&nextAppState);

                // Now set the current state as the next state for the next iter.
                currentAppState = nextAppState;

                // Check if the app is exiting. If it is, then go to the exit state.
                if (nextAppState.gameOver) {
                    state = APP_EXIT;
                }

                break;
            case APP_EXIT:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the exit / gameover screen

                state = APP_EXIT_NODRAW;
                break;
            case APP_EXIT_NODRAW:
                // TA-TODO: Check for a button press here to go back to the start screen

                break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
